export const natures = [
    { name: "" },
    { id: 1, name: "Hardy", increased_stat: "—", decreased_stat: "—", favorite_flavor: "—", disliked_flavor: "—", url: "https://pokeapi.co/api/v2/nature/1/" },
    { id: 2, name: "Bold", increased_stat: "Defense", decreased_stat: "Attack", favorite_flavor: "Sour", disliked_flavor: "Spicy", url: "https://pokeapi.co/api/v2/nature/2/" },
    { id: 3, name: "Modest", increased_stat: "Sp. Attack", decreased_stat: "Attack", favorite_flavor: "Dry", disliked_flavor: "Spicy", url: "https://pokeapi.co/api/v2/nature/3/" },
    { id: 4, name: "Calm", increased_stat: "Sp. Defense", decreased_stat: "Attack", favorite_flavor: "Bitter", disliked_flavor: "Spicy", url: "https://pokeapi.co/api/v2/nature/4/" },
    { id: 5, name: "Timid", increased_stat: "Speed", decreased_stat: "Attack", favorite_flavor: "Sweet", disliked_flavor: "Spicy", url: "https://pokeapi.co/api/v2/nature/5/" },
    { id: 6, name: "Lonely", increased_stat: "Attack", decreased_stat: "Defense", favorite_flavor: "Spicy", disliked_flavor: "Sour", url: "https://pokeapi.co/api/v2/nature/6/" },
    { id: 7, name: "Docile", increased_stat: "—", decreased_stat: "—", favorite_flavor: "—", disliked_flavor: "—", url: "https://pokeapi.co/api/v2/nature/7/" },
    { id: 8, name: "Mild", increased_stat: "Sp. Attack", decreased_stat: "Defense", favorite_flavor: "Dry", disliked_flavor: "Sour", url: "https://pokeapi.co/api/v2/nature/8/" },
    { id: 9, name: "Gentle", increased_stat: "Sp. Defense", decreased_stat: "Defense", favorite_flavor: "Bitter", disliked_flavor: "Sour", url: "https://pokeapi.co/api/v2/nature/9/" },
    { id: 10, name: "Hasty", increased_stat: "Speed", decreased_stat: "Defense", favorite_flavor: "Sweet", disliked_flavor: "Sour", url: "https://pokeapi.co/api/v2/nature/10/" },
    { id: 11, name: "Adamant", increased_stat: "Attack", decreased_stat: "Sp. Attack", favorite_flavor: "Spicy", disliked_flavor: "Dry", url: "https://pokeapi.co/api/v2/nature/11/" },
    { id: 12, name: "Impish", increased_stat: "Defense", decreased_stat: "Sp. Attack", favorite_flavor: "Sour", disliked_flavor: "Dry", url: "https://pokeapi.co/api/v2/nature/12/" },
    { id: 13, name: "Bashful", increased_stat: "—", decreased_stat: "—", favorite_flavor: "—", disliked_flavor: "—", url: "https://pokeapi.co/api/v2/nature/13/" },
    { id: 14, name: "Careful", increased_stat: "Sp. Defense", decreased_stat: "Sp. Attack", favorite_flavor: "Bitter", disliked_flavor: "Dry", url: "https://pokeapi.co/api/v2/nature/14/" },
    { id: 15, name: "Rash", increased_stat: "Sp. Attack", decreased_stat: "Sp. Defense", favorite_flavor: "Dry", disliked_flavor: "Bitter", url: "https://pokeapi.co/api/v2/nature/15/" },
    { id: 16, name: "Jolly", increased_stat: "Speed", decreased_stat: "Sp. Attack", favorite_flavor: "Sweet", disliked_flavor: "Dry", url: "https://pokeapi.co/api/v2/nature/16/" },
    { id: 17, name: "Naughty", increased_stat: "Attack", decreased_stat: "Sp. Defense", favorite_flavor: "Spicy", disliked_flavor: "Bitter", url: "https://pokeapi.co/api/v2/nature/17/" },
    { id: 18, name: "Lax", increased_stat: "Defense", decreased_stat: "Sp. Defense", favorite_flavor: "Sour", disliked_flavor: "Bitter", url: "https://pokeapi.co/api/v2/nature/18/" },
    { id: 19, name: "Naive", increased_stat: "Speed", decreased_stat: "Sp. Defense", favorite_flavor: "Sweet", disliked_flavor: "Bitter", url: "https://pokeapi.co/api/v2/nature/19/" },
    { id: 20, name: "Quirky", increased_stat: "—", decreased_stat: "—", favorite_flavor: "—", disliked_flavor: "—", url: "https://pokeapi.co/api/v2/nature/20/" },
    { id: 21, name: "Brave", increased_stat: "Attack", decreased_stat: "Speed", favorite_flavor: "Spicy", disliked_flavor: "Sweet", url: "https://pokeapi.co/api/v2/nature/21/" },
    { id: 22, name: "Relaxed", increased_stat: "Defense", decreased_stat: "Speed", favorite_flavor: "Sour", disliked_flavor: "Sweet", url: "https://pokeapi.co/api/v2/nature/22/" },
    { id: 23, name: "Quiet", increased_stat: "Sp. Attack", decreased_stat: "Speed", favorite_flavor: "Dry", disliked_flavor: "Sweet", url: "https://pokeapi.co/api/v2/nature/23/" },
    { id: 24, name: "Sassy", increased_stat: "Sp. Defense", decreased_stat: "Speed", favorite_flavor: "Bitter", disliked_flavor: "Sweet", url: "https://pokeapi.co/api/v2/nature/24/" },
    { id: 25, name: "Serious", increased_stat: "—", decreased_stat: "—", favorite_flavor: "—", disliked_flavor: "—", url: "https://pokeapi.co/api/v2/nature/25/" },
];


export const berryID = [
    { name: "cheri", id: 1 },
    { name: "chesto", id: 2 },
    { name: "pecha", id: 3 },
    { name: "rawst", id: 4 },
    { name: "aspear", id: 5 },
    { name: "leppa", id: 6 },
    { name: "oran", id: 7 },
    { name: "persim", id: 8 },
    { name: "lum", id: 9 },
    { name: "sitrus", id: 10 },
    { name: "figy", id: 11 },
    { name: "wiki", id: 12 },
    { name: "mago", id: 13 },
    { name: "aguav", id: 14 },
    { name: "iapapa", id: 15 },
    { name: "razz", id: 16 },
    { name: "bluk", id: 17 },
    { name: "nanab", id: 18 },
    { name: "wepear", id: 19 },
    { name: "pinap", id: 20 },
    { name: "pomeg", id: 21 },
    { name: "kelpsy", id: 22 },
    { name: "qualot", id: 23 },
    { name: "hondew", id: 24 },
    { name: "grepa", id: 25 },
    { name: "tamato", id: 26 },
    { name: "cornn", id: 27 },
    { name: "magost", id: 28 },
    { name: "rabuta", id: 29 },
    { name: "nomel", id: 30 },
    { name: "spelon", id: 31 },
    { name: "pamtre", id: 32 },
    { name: "watmel", id: 33 },
    { name: "durin", id: 34 },
    { name: "belue", id: 35 },
    { name: "occa", id: 36 },
    { name: "passho", id: 37 },
    { name: "wacan", id: 38 },
    { name: "rindo", id: 39 },
    { name: "yache", id: 40 },
    { name: "chople", id: 41 },
    { name: "kebia", id: 42 },
    { name: "shuca", id: 43 },
    { name: "coba", id: 44 },
    { name: "payapa", id: 45 },
    { name: "tanga", id: 46 },
    { name: "charti", id: 47 },
    { name: "kasib", id: 48 },
    { name: "haban", id: 49 },
    { name: "colbur", id: 50 },
    { name: "babiri", id: 51 },
    { name: "chilan", id: 52 },
    { name: "liechi", id: 53 },
    { name: "ganlon", id: 54 },
    { name: "salac", id: 55 },
    { name: "petaya", id: 56 },
    { name: "apicot", id: 57 },
    { name: "lansat", id: 58 },
    { name: "starf", id: 59 },
    { name: "enigma", id: 60 },
    { name: "micle", id: 61 },
    { name: "custap", id: 62 },
    { name: "jaboca", id: 63 },
    { name: "rowap", id: 64 }
];

const gen4Images = [
    "https://archives.bulbagarden.net/media/upload/4/44/Diamond_summary_1.png",
    "https://archives.bulbagarden.net/media/upload/1/13/Diamond_summary_2.png",
    "https://archives.bulbagarden.net/media/upload/3/3e/Diamond_summary_3.png",
    "https://archives.bulbagarden.net/media/upload/d/dc/Diamond_summary_4.png",
    "https://archives.bulbagarden.net/media/upload/0/03/Diamond_summary_5.png",
    "https://archives.bulbagarden.net/media/upload/0/02/Diamond_summary_6.png",
    "https://archives.bulbagarden.net/media/upload/1/19/Diamond_summary_6_desc.png",
    "https://archives.bulbagarden.net/media/upload/2/2d/Diamond_summary_7.png",
    "https://archives.bulbagarden.net/media/upload/e/ee/Diamond_summary_7_desc.png"

];

const gen3Images = [
    "https://archives.bulbagarden.net/media/upload/9/9a/Emerald_summary_1.png",
    "https://archives.bulbagarden.net/media/upload/e/ec/Emerald_summary_2.png",
    "https://archives.bulbagarden.net/media/upload/9/98/Emerald_summary_3.png",
    "https://archives.bulbagarden.net/media/upload/8/81/Emerald_summary_3_desc.png",
    "https://archives.bulbagarden.net/media/upload/4/47/Emerald_summary_4.png",
    "https://archives.bulbagarden.net/media/upload/2/2d/Emerald_summary_4_desc.png",

];

const genImages = [
    "https://archives.bulbagarden.net/media/upload/e/ec/Emerald_summary_2.png",
    "https://archives.bulbagarden.net/media/upload/c/c5/FR_summary_2.png",
    "https://archives.bulbagarden.net/media/upload/c/ca/FR_summary_3.png",
    "https://archives.bulbagarden.net/media/upload/b/b5/FR_summary_3_desc.png"
]